### ISSUE TITLE
Add gray color to icons

### ISSUE THREAD

**Issue by joelhooks** [eggheadio/egghead-ui#100]
We are using the gray color for icons and need it added so it won't be sad about the proptype with regards to color. We might consider adding all of our core colors or perhaps not enforcing it at all?

![image](https://cloud.githubusercontent.com/assets/86834/24567422/7b227efa-1612-11e7-9e9a-72fe7309a4ef.png)

**Comment by trevordmiller** [comment]
This is another reason why this story would be very helpful:
https://github.com/eggheadio/tachyons-egghead/issues/28

Then you could have any components that have a `color` prop use:

```
import colors from 'egghead-colors'

...

Thing.propTypes = {
  color: oneOf(colors),
}
```
