### ISSUE TITLE
Polish LessonActions component

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-ui#109]
# Changes

The `LessonActions` component needs a few style tweaks:
- [x] A max width should be added to the lesson actions on desktop to better match the mocks
- [x] A left border should be added on the first lesson action on desktop to better match the mocks
- ~Don't display Replace and Upload on phone/tablet~
- [x] Smaller containers should look better

# Mocks

https://app.zeplin.io/project.html#pid=58caceae349a0d1341e322a5&sid=58db9d6f43c40c913fc802fa

**Comment by trevordmiller** [comment]
I don't want to disable replace/upload based on screen size because I'm using container sizes for everything else, and I don't want to disable replace/upload based on feature detection with something like modernizr because 1) it requires a custom build and 2) pretty much all modern devices, mobile or desktop, have the File API and can upload files; so theoretically instructors could have a video on their mobile device and still replace/upload. But, I feel this would cause more complexity and confusion than is worth (if an instructor views on mobile how would they know they can replace/upload on desktop?). I feel instructors are smart enough to use desktop if something doesn't work on mobile so I'm tabling that piece of this story for now. We can address later if needed.

**Comment by joelhooks** [comment]
Tabling until when? I don't agree with this decision and prefer to not show functionality that doesn't make sense on a given platform.

**Comment by trevordmiller** [comment]
@joelhooks When you say on a given platform, are you referring to a screen width? Because modern platforms all support the file API. If so, what screen width would you classify as "desktop"? Some tablets have a larger screen width than small desktops, for example - not even including orientation.

**Comment by trevordmiller** [comment]
I don't understand the benefit of hiding things, when the functionality exists; you could upload or replace a video on modern mobile devices if you wanted.

**Comment by trevordmiller** [comment]
I'd rather not start introducing arbitrary screen-width based features unless there are specific browsers/devices/screen sizes that should be omitted for a feature.

**Comment by trevordmiller** [comment]
I'll assume 1200px total screen width and up is desktop, feels dirty but should work fine
