### ISSUE TITLE
Replace /package link building with hypermedia

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-ui#113]
I've been able to replace any link building in egghead-ui pieces with hypermedia URLs except for a couple places:
- `instructor.courses_url`: there is `root.instructor_series_url`) but that is only for the logged in instructor; seems that if an instructor has at least one course published they should get a `instructor.courses_url` like they have a `instructor.lessons_url`. The current link building is in `InstructorStats`.
- `root.technologies_url`. The current link building is in `ProposeLessonForm`.

**Comment by trevordmiller** [comment]
Should be ready to go now that this is out: https://github.com/eggheadio/egghead-rails/pull/1357#pullrequestreview-33824669

**Comment by theianjones** [comment]
Should we rename the `series_url` to `courses_url` on the [user object](https://github.com/eggheadio/egghead-rails/blob/master/app/views/api/v1/users/_user.json.jbuilder#L12)? I just added this. The review app is the only front end piece that uses it as of right now.

**Comment by trevordmiller** [comment]
@ijones16 Some endpoints use "series", some "courses" - would be nice to start using "courses" going forward. It shouldn't be on the user object should it? IMO the root api/v1 should have a "courses_url" (currently "series_url") which gives all courses, and then the instructor should have instructor.courses_url - specific to the instructor

**Comment by trevordmiller** [comment]
But I'm cool with whatever as long as I can use it. Up to you and @peterkeen

**Comment by peterkeen** [comment]
`Series` et. al. should be completely internal to `egghead-rails`. Everything public facing, including the API, should say `courses`. The fact that courses are currently implemented with the `Series` object is an implementation detail.

**Comment by peterkeen** [comment]
(this is something that I have done a bad job communicating)
