### ISSUE TITLE
Address SSR issues

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-ui#140]
Local storage shouldn't be used directly (could probably just `get(localStorage, 'token')` with lodash). Are there any other issues? Is there an eslint plugin to catch these issues before pushing them?

**Comment by trevordmiller** [comment]
I'd like to spend 30 minutes swaping out react-scripts (cra) with next for a SSR environment to catch issues

**Comment by trevordmiller** [comment]
Related issue in Chart.js: https://github.com/chartjs/Chart.js/pull/3909

**Comment by joelhooks** [comment]
We use master of Chart.js and it functions as expected with SSR. https://github.com/eggheadio/egghead-rails/blob/master/client/package.json#L52

**Comment by trevordmiller** [comment]
That works for now; we should use a specific version after they cut the next release though as master is unstable
