### ISSUE TITLE
Improve lesson actions

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-ui#145]
Feedback from new instructors: Lesson actions don't appear as call to actions, the icons are confusing since they match the todo list (we need unique icons for [each possible lesson state](https://github.com/eggheadio/egghead-ui/blob/master/src/package/utils/lessonStates/index.js#L4-L82)), and Joel suggested the lesson actions could have less-terse text, although with the current design there isn't much room for more than 1-3 words.

**Comment by trevordmiller** [comment]
![image](https://cloud.githubusercontent.com/assets/5497885/25716854/d4afaa40-30bd-11e7-8c5d-44442f6a8943.png)

**Comment by trevordmiller** [comment]
@vojtaholik Can you please look into this when you have a chance? We need to consider every possible lesson state from here:
https://github.com/eggheadio/egghead-ui/blob/master/src/package/utils/lessonStates/index.js#L4-L82

**Comment by joelhooks** [comment]
@trevordmiller @vojtaholik there's been [a lot of thought](https://paper.dropbox.com/folder/show/Instructor-Center-e.iX7ZavGxujPFwhjOZcQs9wM75WdG5Qz8ElgJ2CUTM2Ywfb1nD9), which might be a better launching point for design consideration than lines of js.

Can we close this in favor of https://github.com/eggheadio/egghead-ui/issues/142 please?

**Comment by trevordmiller** [comment]
@joelhooks Yep hadn't seen that yet
