### ISSUE TITLE
The revenue graph makes the initial page scroll horizontally

### ISSUE THREAD

**Issue by beeman** [eggheadio/egghead-ui#149]
As seen on the screenshot the revenue graph causes the page to scroll. If I recall correctly this is something that got changed not too long ago.

![image uploaded from ios 1](https://cloud.githubusercontent.com/assets/36491/25727092/ef771a32-30ec-11e7-8e6a-0629ca7066f2.jpg)

**Comment by trevordmiller** [comment]
Thanks for letting us know @beeman, this may be an issue with mobile safari. Will look into it.

**Comment by trevordmiller** [comment]
Confirmed this is a race condition with the `ContainerWidth` component wrapper for container-query-esque styles. A fix is in progress.

**Comment by trevordmiller** [comment]
It has to do with the way that Chart.js measures the dom container width with JavaScript on dom load. Have a solution in the works.

![image](https://cloud.githubusercontent.com/assets/5497885/25870085/08d10eee-34c0-11e7-928d-3a5dc67c8b7a.png)

![image](https://cloud.githubusercontent.com/assets/5497885/25870533/9e2f1944-34c1-11e7-97d4-a3607be36bb7.png)

**Comment by trevordmiller** [comment]
Fixed. Going out in next release. Thanks for the info @beeman.
![fix-revenue](https://cloud.githubusercontent.com/assets/5497885/25871618/6975d586-34c5-11e7-86af-1ef96397676b.gif)
