### ISSUE TITLE
Side menu on mobile is opened by default

### ISSUE THREAD

**Issue by beeman** [eggheadio/egghead-ui#150]
The side menu on mobile is opened by default whereas before it was closed.

Probably related to #149, which makes the viewport larger than expected. 

![image uploaded from ios](https://cloud.githubusercontent.com/assets/36491/25727078/df7ce5e4-30ec-11e7-94e8-642a799d9bc4.jpg)

**Comment by trevordmiller** [comment]
Thank you for the issue @beeman; will look into this.

**Comment by trevordmiller** [comment]
Not related to 149, but I know what the problem is. In progress.

**Comment by trevordmiller** [comment]
Waiting for [the latest egghead-ui PR](https://github.com/eggheadio/egghead-ui/pull/157) to be approved and merged so I can upgrade the egghead-instructor-center and fix this.

**Comment by trevordmiller** [comment]
@beeman This has been fixed and will go out in the next release:
![responsive-navigation](https://cloud.githubusercontent.com/assets/5497885/25917452/549a7f8e-3585-11e7-9220-afdd9ee1650b.gif)

Thanks for your help!

**Comment by beeman** [comment]
Thanks for fixing it so fast @trevordmiller 👍

**Comment by trevordmiller** [comment]
@beeman No problem. Appreciate your issue; it's been released to prod: https://instructor.egghead.io/.

If you are interested in contributing in the future, I'd like to set up a test account for you:
https://github.com/eggheadio/egghead-ui/issues/152

**Comment by beeman** [comment]
@trevordmiller just confirmed that both issues are fixed!  

I'm interested in that for sure.
