### ISSUE TITLE
Promote Instructor Center "List"

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-ui#73]
The `List` component is currently implemented in the Instructor Center:
https://github.com/eggheadio/egghead-instructor-center/blob/master/src/components/List/index.js

All it does is accept a list of items, and renders them stacked vertically with A) a light border on the bottom of every item but the last and 2) equal padding around each item. It is often used inside of a `Card` component directly.

egghead-rails is now using `List`:
https://github.com/eggheadio/egghead-rails/pull/1211/files
so it would be good to promote and consumed it in both projects from egghead-ui.

## Examples from mocks

`List` was first designed in the Instructor Center mocks from @vojtaholik:

![image](https://cloud.githubusercontent.com/assets/5497885/24075477/f97ba06e-0be1-11e7-8118-ca42126b813c.png)

![image](https://cloud.githubusercontent.com/assets/5497885/24075479/01c21424-0be2-11e7-9cea-a34e2f71e72b.png)

![image](https://cloud.githubusercontent.com/assets/5497885/24075481/078d828a-0be2-11e7-93b1-ef5e09d41062.png)

![image](https://cloud.githubusercontent.com/assets/5497885/24075483/147c6966-0be2-11e7-921e-e2c3feb67206.png)

## Examples currently in Instructor Center

![image](https://cloud.githubusercontent.com/assets/5497885/24075495/4bbd8ac2-0be2-11e7-9abd-a059a7285490.png)

![image](https://cloud.githubusercontent.com/assets/5497885/24075498/55474056-0be2-11e7-9726-2fe970e991e4.png)

![image](https://cloud.githubusercontent.com/assets/5497885/24075503/5ebe93aa-0be2-11e7-8af2-2c93d3c485da.png)

## Example composition

In the instructor center, the `Card` component owns the border radius and drop shadow styling, list has none of that itself. So a `List` is often put inside a `Card`. You'll notice this `List` component is very simple. I much prefer these types of simple components that do just one thing, rather than have a bunch of config and formatting options. That way they can be composed together using `children`. Here is an example of how the `egghead-rails` `LessonList` could be created with composition of components like `List`:

- [`Card`](https://github.com/eggheadio/egghead-instructor-center/blob/master/src/components/Card/index.js) would need to be promoted to egghead-ui as well; it only concerns itself with the rounded corners and drop shadow).
- [`List`](https://github.com/eggheadio/egghead-instructor-center/blob/master/src/components/List/index.js) - from this PR would be promoted to egghead-ui; it only concerns itself with borders and padding of items.
- `LessonList` only exists in `egghead-rails` and composes together `Card` and `List` with egghead-rails specific sub-components and logic like this:

```
import React from 'react'
import {map} from 'lodash'
import {Card, List} from 'egghead-ui'
import PlayCourse from './components/PlayCourse'
import LessonListItem from './components/LessonListItem'

const LessonList = ({lessons, course}) => (
  <Card>
    {course
      ? <PlayCourse />
      : null
    }
    <List items={map(lessons, lesson => (
      <LessonListItem lesson={lesson} />
    ))} />
  </Card>
)

export default LessonList
```

![lesson-list-composition-example](https://cloud.githubusercontent.com/assets/5497885/24076924/da1f4772-0c02-11e7-8bd3-488cb3559000.png)

In summary: promote generic, single responsibility components in egghead-ui; then compose these things together with project specific logic and sub-components to create screens.

Here are a couple examples of this in the Instructor Center of how this type of minimal `children` composition works:
- https://github.com/eggheadio/egghead-instructor-center/blob/master/src/screens/Instructors/screens/Instructor/components/InstructorInfoCard/index.js
- https://github.com/eggheadio/egghead-instructor-center/blob/master/src/screens/Dashboard/components/HelpCard/index.js

Would be good to update the project README with a link to this PR as a complete example.

**Comment by vojtaholik** [comment]
Example of List breakdown: https://zpl.io/ZddDih
- this is a latest up-to-date design for lists, it has new colors, shadow definitions, comments regarding interactions and such.

Feel free to use it as example, I think it can easily carry a variety of different data.

There's a bridge between this list and list of lessons in IC -> in IC, there's a "responsive" / less wide version present, but overally it should be the same. **I'm really just copying those lists in sketch and making them different width etc.** If shaka team handles the responsivity right, it should be enough to re-use this component anywhere. ;)

**Variations**
- list of lessons, courses, playlists (egghead.io), can be enhanced with search and sorting/filtering functionality
- list of lessons, courses, playlist **with actions** (IC)
- list of tasks (To Do in IC)
- Guide in IC
- Propose a Topic list in IC

I think that basic structure is the same for all of them, the rows differ though, I propose to use classes like this: 
```
<list><task>
<list><task><actions>
<list><text><button>
```
_but this is obviously your cup of tea. :)_


**edit:** You could also say that list can be part of other card, like this: 
![list](https://cloud.githubusercontent.com/assets/25487857/24150748/f58158d4-0e46-11e7-9ab3-00971c4413f7.png)

**Comment by joelhooks** [comment]
This looks ready to go to me.

**Comment by trevordmiller** [comment]
Sounds great. I'm moving this to the "Ready to implement" column. @tayiorbeii, would mind taking on this story? To be clear, it is just the promotion of [the Instructor Center `List` component to `egghead-ui`](https://github.com/eggheadio/egghead-instructor-center/blob/master/src/components/List/index.js). The examples Vojta posted are ways it will be composed in other components like `LessonList` in `egghead-rails` and are not included in this story.

**Comment by trevordmiller** [comment]
I'm grabbing this since Taylor is busy with the tachyons-egghead simplifying forks.
