### ISSUE TITLE
Replace react-storybook for styleguide creation

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-ui#74]
Currently we are using [react-storybook](https://github.com/storybooks/react-storybook) to create the styleguide app piece of egghead-ui, which gets published to http://styleguide.egghead.io. It would be good to move to another solution (potentially build our own open source package) since the company behind storybook has folded and we don't need all the config it offers.

# How react-storybook is used currently in egghead-ui

Each component in the library API (exported from `src/index.js`) has it's own folder in `src/components/{SomeComponent}` with a `src/components/{SomeComponent}/index.examples.js` file.

![image](https://cloud.githubusercontent.com/assets/5497885/24123996/5b24e694-0d87-11e7-9417-86a6df3b23dc.png)

These example files are wired up in the `.storybook` directory to render two types of pages per component:

## Info pages

The "Info" page provides documentation with an example and props table generated automatically from the sibling `index.js` file:
![image](https://cloud.githubusercontent.com/assets/5497885/24123906/158e1a2e-0d87-11e7-9cc5-cbaf1b74daba.png)

## Combinations pages

The "Combinations" page automatically renders all possible props combinations generated automatically from the sibling `index.js` file:
![image](https://cloud.githubusercontent.com/assets/5497885/24123935/2eb270f4-0d87-11e7-9da7-1faa0bb1539e.png)

# Proposal

It would be nice if we could replace all these dependencies, config, and example files with a single open source package that renders documentation and prop combinations automatically from component source files.

**Comment by vojtaholik** [comment]
Wouldn't be better to work on components/pages and define all the buttons, icons and elements **on the go**, while adding them to a "library" _and re-using when and where we want?_ That way we could see what does really work and what we really need.

**Comment by joelhooks** [comment]
@trevordmiller would you write this as part of egghead-ui initially? Feels like a full on project.

**Comment by trevordmiller** [comment]
> "would you write this as part of egghead-ui initially? Feels like a full on project."

@joelhooks I would imagine this would work best as an open source npm package in it's own repo (either in a personal repo or as part of the egghead org). I'm planning to do this in my own GitHub and then use it here, but am trying not to specify implementation details ;)

**Comment by trevordmiller** [comment]
> "Wouldn't be better to work on components/pages and define all the buttons, icons and elements on the go, while adding them to a "library" and re-using when and where we want? That way we could see what does really work and what we really need."

@vojtaholik Yes, that is the plan. Which is why we have this issue to get back to that: https://github.com/eggheadio/egghead-ui/issues/75
This story is just to change the underlying engine/config for how we render the docs + examples from the components that do get put in `egghead-ui` after they have been battle tested in a project and promoted here.

**Comment by joelhooks** [comment]
I would recommend capturing this in a Paper doc at this point, as it is tangentially related to `egghead-ui` and is mid to far future work.

**Comment by trevordmiller** [comment]
https://paper.dropbox.com/folder/show/egghead-ui-e.iX7ZavGxujPFwhjOZcQs9wNRG3Adn3OYQVaPVEEVnnqeU48mzY
