### ISSUE TITLE
Remove unused components

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-ui#75]
Some components were built directly in egghead-ui before first being used in an egghead project; because of this, their prop types and layout composition haven't been tested. In the future, it would be better to implement components/utils directly in a project and then discuss and promote to egghead-ui as needed so that components in egghead-ui are battle tested and ready for use across projects. This is what I suggest we do going forward. But to get on track with this, I propose we remove the following from `egghead-ui`:
- `utils/formClassNames.js`
- `Checkbox`
- `Input`
- `RadioGroup`
- `Tooltip`

These are not in use in any egghead projects so it shouldn't be a problem to remove them, and then `egghead-rails` can implement them directly (reusing some of the code from the remove PR if desired). If and when they should be promoted back into egghead-ui we can add separate stories on the egghead-ui board and discuss it first.

After this is done, the project will be left with only components that are being used by egghead projects currently, which we can continue to iterate on and improve; so we can share that with the team and designers for review.

Can replace .npmignore with package.json files

Can move contributing info into CONTRIBUTING

**Comment by vojtaholik** [comment]
Makes sense to me.

**Comment by joelhooks** [comment]
@tayiorbeii you should capture this work, for reference if nothing else. We could just toss it in a "lost toys" repo. They will all be needed in the future.

**Comment by trevordmiller** [comment]
Sounds like this is ready to be implemented and @tayiorbeii plans to work on it. I'm moving it to the "ready to implement" column.

**Comment by tayiorbeii** [comment]
@trevordmiller @joelhooks Pushed the components listed above to https://github.com/eggheadio/egghead-ui-vault

I didn't create a `master` branch first, but it looks like they made it there just fine.

**Comment by trevordmiller** [comment]
Cool, thanks Taylor

**Comment by trevordmiller** [comment]
Implemented and waiting for review on https://github.com/eggheadio/egghead-ui/pull/82#pullrequestreview-28530290
