### ISSUE TITLE
Promote egghead-ui "Loading" sub-component

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-ui#76]
Currently, the `Request` component has a `Loading` sub-component. This used to be exposed directly, but I (Trevor) made the mistake of moving it into `Request` as I thought it was only being used there. We need to promote it back up to it's own exported component, independent of `Request`.

https://github.com/eggheadio/egghead-ui/tree/master/src/components/Request

egghead-rails is needs to use it directly:
https://github.com/eggheadio/egghead-rails/pull/1211/files#diff-333c4a33c8171c0f73d201d718dafa85

**Comment by trevordmiller** [comment]
Hey @ijones16, would you mind tackling this one?

**Comment by theianjones** [comment]
When promoting components in egghead-ui, what is the process around updating IC and egghead proper? Just update when you need it? Obviously, communication will make that easier.

**Comment by trevordmiller** [comment]
@ijones16 Here is the full process to adding a component to `egghead-ui`:
1) create a feature branch off of `egghead-ui` master.
2) in `egghead-ui`, add the new component to `src/components/{NewComponent}/index.js`; in this case since the component already exists in `egghead-ui` but isn't exposed at the top level, you'll just need to move `src/components/Request/components/Loading/` to `src/components/Loading` and update the uses in `src/components/Request` to point to the new path.
3) Add a new `src/components/Loading/index.examples.js` with an `Info` and `Combinations` config; check out all the other `src/components/*/index.examples.js` to see how these work and let me know if any of it is unclear. Run `yarn dev:styleguide` and open `localhost:2000` to view this - you should see a new "Loading" option where you can veiw your new documentation and examples rendered from `src/components/Loading/index.examples.js` automatically.
4) Expose this new component by adding it to `src/index.js` like the other public components.
5) Stage, commit, and push as normal.
6) Run `yarn bump` to bump the version for a new npm release; in this case since it is a new feature I would bump the "minor" number (ie `3.3.1` -> `3.4.0`).
7) Submit your pull request; once it is merged `styleguide.egghead.io` will be updated with what you saw at `localhost:2000` and npm will be updated so projects can `yarn upgrade egghead-ui` and then `import {Loading} from 'egghead-ui'`.

Make sense? This info is in the README, but let me know if any of it is confusing and I can update it. Happy to help as well if needed, just let me know :)

**Comment by theianjones** [comment]
That makes sense :) I was thinking more about keeping other projects up to date with egghead-ui. IE Right now egghead proper defines its own loading component and once this loading component (the one in Request) gets promoted up to egghead ui, we dont want the component in egghead proper, we now want to use the new component from egghead-ui. It is probably a non issue though "just update the component when this happens".

**Comment by trevordmiller** [comment]
@ijones16 oh I see. I believe this is my job as the technical owner of `egghead-ui` - once a new component is in the library, educate the team to be able to use it. But with the version bumps, it means projects can upgrade and adopt whenever they are ready without breaking anything in the meantime.

**Comment by joelhooks** [comment]
@trevordmiller or delegate it! :)

**Comment by trevordmiller** [comment]
@joelhooks for sure. Either way, I'll make sure when a new component get's added to `egghead-ui` that the team knows and will take on upgrading projects or delegate to others so we can all stay in sync :)

**Comment by trevordmiller** [comment]
@ijones16 Here is a full example PR with the `List` component I just promoted from egghead-instructor-center to egghead-ui: https://github.com/eggheadio/egghead-ui/pull/80#pullrequestreview-28500402

**Comment by theianjones** [comment]
#83 resolves this
