### ISSUE TITLE
Add ChevronDown to <Icon/>

### ISSUE THREAD

**Issue by theianjones** [eggheadio/egghead-ui#87]
The header component in egghead-rails, needs an ChevronDown Icon.

When egghead-ui promotes a dropdown component [[disscussed here](https://github.com/eggheadio/egghead-rails/pull/1170)], we will need one anyway!

**Comment by trevordmiller** [comment]
Sounds good @ijones16. I put it in the "Ready to implement" column. Do you mind taking care of this one?
https://github.com/eggheadio/egghead-ui/projects/2

**Comment by theianjones** [comment]
will do!
