### ISSUE TITLE
Promote egghead logo

### ISSUE THREAD

**Issue by theianjones** [eggheadio/egghead-ui#90]
Instructor center currently defines logo: 
https://github.com/eggheadio/egghead-instructor-center/tree/master/src/components/Logo

We are now using the logo in egghead, in the header: 
https://github.com/eggheadio/egghead-rails/blob/master/client/app/components/Header/index.js

This component will display our egghead logo. One difference to consider is that the logo in IC is responsive while the one in egghead (currently) is not. This could be passed as a param.

egghead proper logo:
![](https://d3vv6lp55qjaqc.cloudfront.net/items/3Z2T2w3m3O0J460U3p0y/Screen%20Recording%202017-03-24%20at%2001.29%20PM.gif?v=f21cd2f8)

IC egghead logo:
![](https://d3vv6lp55qjaqc.cloudfront.net/items/311Z0L2I0t3i3Q3h2s3t/Screen%20Recording%202017-03-24%20at%2001.31%20PM.gif?v=7c6f61d3)

**Comment by trevordmiller** [comment]
@ijones16 Good idea. Maybe we could have a single `Logo` component which can be `small` (eggo only) which could be used in both projects and then default which could be eggo + egghead.io which egghead-rails could use; then the IC can compose `<Logo small` + IC specific text?

@vojtaholik, @joelhooks, @tayiorbeii, @DrShpongle what are your thoughts on this?

**Comment by tayiorbeii** [comment]
Good catch & ideas!

**Comment by joelhooks** [comment]
This will have an "overDark" option, as the eggo logo changes as does the text color.

The actual eggo itself can be an svg Icon + variants?

**Comment by trevordmiller** [comment]
That sounds like a good idea Joel.

**Comment by trevordmiller** [comment]
Here is the instructor center logo implementation which could be a good starting point if anyone wants to take a whack at this:
https://github.com/eggheadio/egghead-instructor-center/tree/master/src/components/Logo
