### ISSUE TITLE
Polish Button component

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-ui#93]
Vojta has proposed some changes to the `Button` component in his latest styleguide mocks:
https://egghead.invisionapp.com/d/main#/console/10384631/225150686/comments/79600739

## Current

http://styleguide.egghead.io/?selectedKind=Button&selectedStory=Info&full=0&down=1&left=1&panelRight=0

## Proposed changes

- Update the `size` options to `small`, `medium`, `large`, and `xlarge`
- Add a minimum width to all but the `small` size button
- Make them all pill style instead of having a `pill` option
- Color options can be any of `colors`; defaults to `orange`
- `outline` can be `true` or `false`, defaults to `false`
- Add active/focus/hover states box shadow instead of color change
- Bump breaking change
- Use in instructor center

![image](https://cloud.githubusercontent.com/assets/5497885/24370544/02727f1c-12e5-11e7-868d-f54549267b47.png)

**Comment by joelhooks** [comment]
Button "levels" doesn't make sense to me at all. They aren't hierarchical containers. 

@vojtaholik is using colors to represent content types, so defaulting buttons to one of those colors might be weird. I'd consider defaulting to a neutral color.

**Comment by trevordmiller** [comment]
@joelhooks Sounds good, changed `levels` back to `sizes` as it currently is. But we do need to figure out what these sizes should be.

**Comment by vojtaholik** [comment]
Updated [styleguide](https://egghead.invisionapp.com/share/5WAZLYTET) with one more button size, now we have **S (h32 with special padding [24px] and no min-width set)**, M (h40), L (h48), XL (h56)

**Comment by trevordmiller** [comment]
Thanks @vojtaholik. I'll update this issue to match.
