### ISSUE TITLE
Polish List component

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-ui#94]
Vojta has proposed some changes to the `List` component in his latest styleguide mocks:
https://egghead.invisionapp.com/d/main#/console/10384631/225150686/comments/79600739

## Current

http://styleguide.egghead.io/?selectedKind=List&selectedStory=Info&full=0&down=1&left=1&panelRight=0

## Proposed changes

- Add a `size` option of oneOf `small` `medium` or `large`, default `medium`; with each size adding more padding to each item.
- Add `overDark` option which changes the default `gray-secondary` bottom border to `dark-blue`

![image](https://cloud.githubusercontent.com/assets/5497885/24334003/b16bdbce-121f-11e7-846b-18beb5bf1079.png)

![image](https://cloud.githubusercontent.com/assets/5497885/24334064/d111e5c6-1220-11e7-811d-7a28dc690dbd.png)

Note that most of these mocks show a `List` inside of other components like a `Card`, but the list doesn't dictate the white background color or rounded borders or three dot menus etc., it is just the veritical list of items with padding and bottom border on each item but the last.

**Comment by joelhooks** [comment]
https://github.com/eggheadio/egghead-rails/blob/master/client/app/components/ContentList/index.js

**Comment by trevordmiller** [comment]
@joelhooks What is the purpose of that link? In my eyes `ContentList` should be an instance of `List` that isn't promoted to `egghead-ui` yet - it is only in `egghead-rails` for now, where the container `List` is in egghead-ui (the padding on items and bottom border on each item but the last).

**Comment by theianjones** [comment]
If we are using size instead of level for the buttons, would it make sense to do the same here?

**Comment by trevordmiller** [comment]
> "If we are using size instead of level for the buttons, would it make sense to do the same here?"

@ijones16 Yeah you're probably right. As Joel suggested in the button comment, let's reserve `level` for components that have a hierarchy like `Card` and `Heading`, and `size` if not. I updated the description ^

**Comment by trevordmiller** [comment]
Resolved by https://github.com/eggheadio/egghead-ui/pull/132
