### ISSUE TITLE
Promote Tabs component

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-ui#95]
Vojta has proposed promoting the instructor center `Tabs` component to egghead-ui in his latest styleguide mocks:
https://egghead.invisionapp.com/d/main#/console/10384631/225150686/comments/79600739

## Current

https://github.com/eggheadio/egghead-instructor-center/blob/master/src/components/Tabs/index.js

![image](https://cloud.githubusercontent.com/assets/5497885/24334031/3b5921de-1220-11e7-991a-a4783998c387.png)

![image](https://cloud.githubusercontent.com/assets/5497885/24334034/420c0992-1220-11e7-91ba-44eaf0fcab8c.png)

Mobile:
![image](https://cloud.githubusercontent.com/assets/5497885/24334039/4d5b32f0-1220-11e7-9619-34f69cee2a7e.png)

Note that the background appears white in these instances because currently the `Tabs` instances inside the instructor center are always in a `Card` component, but the background color is transparent.

## Proposed changes

None, promote to egghead-ui as is. Mocks show an example with the entire tabs in a `Card`, and just the tab bodies in a `Card` which both are already possible with current implementation:

![image](https://cloud.githubusercontent.com/assets/5497885/24334027/2c702eba-1220-11e7-83ed-4edd46c017ff.png)

**Comment by tayiorbeii** [comment]
Fixed via https://github.com/eggheadio/egghead-ui/pull/102
